name: Typecheck, Lint and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
      REACT_APP_S3_BASE_URL: https://coordinape.s3.amazonaws.com
      REACT_APP_API_BASE_URL: https://myvault.live/api
      ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: nodeModules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: '**/hardhat/node_modules'
          key: hardhatNodeModules-${{ runner.os }}-${{ hashFiles('**/hardhat/yarn.lock') }}

      - run: yarn --frozen-lockfile
      - run: yarn typecheck
      - run: yarn lint:check
      - run: yarn prettier:check
      - run: git submodule update --init --recursive
      - run: yarn hardhat:install --frozen-lockfile
      - run: yarn hardhat:build
      - run: yarn test:ci
